[package]
name = "themis-client-rs"
version = "0.1.0"
authors = ["gpestana <g6pestana@gmail.com>, Genysys<samuel.b.dare@gmail.com>"]
edition = "2018"

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
ethabi = "11.0.0"
primitive-types = "0.6.0"
hex = "*"
bn = "0.4.3"
rand= "*"