[package]
name = "themis_client"
version = "0.1.0"
authors = ["gpestana <g6pestana@gmail.com>, Genysys<samuel.b.dare@gmail.com>"]
edition = "2018"

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
elgamal_bn = { git = "https://github.com/brave-experiments/elgamal_bn" }
ethabi = "11.0.0"
primitive-types = "0.6.0"
hex = "*"
rand = {version = "0.5", default-features = true}
bn = {git = "https://github.com/paritytech/bn"}
