[package]
name = "themis-client-rs"
version = "0.1.0"
authors = ["gpestana <g6pestana@gmail.com>"]
edition = "2018"

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
elgamal_ristretto = { git = "https://github.com/iquerejeta/elgamal" }
